CONFIG_STDOUT_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_LOG=y

CONFIG_ADC=y
CONFIG_ADC_ASYNC=y
CONFIG_POLL=y

CONFIG_MAIN_STACK_SIZE=2048
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_BT=y
CONFIG_BT_BROADCASTER=y
CONFIG_BT_DEVICE_NAME="nRF54L15DK" 

CONFIG_DEBUG=y
CONFIG_DEBUG_OPTIMIZATIONS=y      # -Og instead of -O2, keeps debug info
CONFIG_DEBUG_THREAD_INFO=y        # thread info visible in Ozone
CONFIG_STACK_SENTINEL=y           # catch stack overflows
CONFIG_STACK_USAGE=y              # track stack high watermark
CONFIG_THREAD_ANALYZER=y          # dump thread info at runtime

CONFIG_SEGGER_SYSTEMVIEW=y
CONFIG_TRACING=y
CONFIG_THREAD_NAME=y
